session/session_inception.go
=> Fix check field default null(json,text,blob)

config/config.go, config/config.toml.example, session/session_inception.go, session/session_inception_test.go
添加单表存在多个current_timestamp的限制检查
=> Add-checkTimestampCount

config/config.go, session/errors.go, session/session_inception.go, session/session_inception_exec_test.go, session/session_inception_test.go
增加建表时 索引名可以不设置的功能, 增加其配置选项check_null_index_name;
=> 增加建表时 索引名可以不设置的功能, 增加其配置选项check_null_index_name;

config/config.go, session/session.go, session/session_inception.go, session/session_inception_backup_test.go
添加统计功能，通过参数`enable_sql_statistic`启用。
兼容`inception`的统计规则和格式。
相比`inception`的优化：如果执行阶段失败时，会正确记录成功操作数。
=> feature: 添加统计功能

config/config.go, session/errors.go, session/session_inception.go, session/session_inception_test.go
添加参数`check_column_position_change`,可控制是否检查列位置/顺序变更,默认为`false`
相关请求:  #40
=> feature: 添加参数check_column_position_change,可控制是否检查列位置/顺序变更

session/session_inception.go, session/session_inception_test.go
** 添加以下规则审核：**
- 子查询表达式
- 字符串、日期、数学、聚合函数表达式
- IN、LIKE、正则表达式等
=> update: 优化审核细节,审核子查询,函数等表达式

session/session_inception.go
添加调用参数：
* sleep 执行 `sleep_rows` 条SQL后休眠多少毫秒。用以降低对线上数据库的影响。单位为毫秒，最小值为0，即不设置，最大值为100000，即100秒。默认值 `0` 
* sleep_rows 执行多少条SQL后休眠一次。最小值为1，默认值 `1`
**该功能默认关闭。**
建议参数 `sleep_rows` 设置大一些，以免性能下降。
=> feature: 添加sleep执行等待功能,降低对线上数据库的影响

config/config.go, config/config.toml.example, session/errors.go, session/session_inception.go, session/session_inception_test.go
添加 check_float_double 参数，为 true 时，需要将 float/double 转成 decimal 数据类型。 默认为 false
=> 新增 float double 审核功能

session/errors.go, session/session_inception.go, session/session_inception_exec_test.go, session/session_inception_test.go
完善外键的审核规则
相关问题：https://github.com/hanchuanchuan/goInception/issues/68
=> update foreign key

session/session_inception.go, session/session_inception_test.go
=> update: 修复add操作无法命中merge_alter_table检测的问题 fix #79

config/config.go, session/parser.go, session/session_inception_backup_test.go
添加选项`enable_minimal_rollback`，设置是否启用最小化回滚SQL，当开启时，update的回滚语句仅记录最小化变更(未变更列不再记录)
=> feature: 添加最小化回滚SQL设置项

config/config.go, docs/options.md, session/session_inception.go
=> Fix wait timeout

session/errors.go
=> fix: 修改列未设置默认值时的提示信息

session/session_inception.go
=> 修复多线程下解析options出现线程安全问题bug

config/config.go, session/parser.go, session/session_inception.go, session/session_inception_backup_test.go
仅在无法正确解析字符类型后, 以十六进制形式转储
受影响的数据类型有 BINARY，VARBINARY，BLOB
=> feature: 添加新参数hex_blob以支持回滚时解析二进制类型

session/session.go, session/session_inception.go, session/session_inception_backup_test.go, session/session_inception_common_test.go, session/session_inception_exec_test.go, session/session_inception_test.go
基于mysql的`lower_case_table_names`变量优化审核规则.
优化测试用例结构.
=> 优化对象名大小写审核规则

session/session_inception.go, session/session_inception_backup_test.go, session/session_inception_common_test.go, session/session_inception_exec_test.go, session/session_inception_test.go
支持update set多表更新语句的审核和执行，
暂不支持多表回滚（仅生成第一个set字段对应的表相应回滚SQL）
相关问题 #112
=> update: 支持update多表更新(暂不支持多表回滚)

session/const.go, session/session_inception.go, session/session_inception_exec_test.go, session/session_inception_test.go
优化列类型变更审核，优化以下实现：
* 长度变小时
* 忽略 `smallint -> int` 等安全的转换
issue: #121
=> update: 优化列类型变更审核

docs/ghost.md
```
ghost_heartbeat_interval_millis 
ghost_max_lag_millis
```
=> 优化ghost文档说明：参数单位为ms

session/conn.go, session/session.go, session/session_inception.go, session/session_inception_common_test.go, session/session_inception_tran_test.go
在开启事务时`--trans`，如果DDL操作在DML操作之后，可能会导致连接找不到数据库。
=> fix: 修复在事务中DDL和DML混合执行时可能出错的问题 (#182)

expression/builtin_info.go, expression/integration_test.go, go.mod, go.sum, owner/manager.go, session/common.go, session/conn.go, session/helper.go, session/helper_test.go, session/inception_result.go, session/session.go, session/session_backup.go, session/session_inception.go, session/sql_split.go, session/tidb_check.go, sessionctx/context.go, table/tables/tables.go, util/mock/context.go
=> Update remove useless code

session/parser.go
=> update: 支持当开启ssl时的binlog解析

session/session.go, session/session_inception.go, session/session_inception_exec_test.go, session/session_inception_test.go, session/tidb_check.go
=> update: 加载数据库默认字符集,优化字符类型长度审核

session/common.go, session/session_inception.go
完善严格模式下的insert列值检查
- string写入int列
该功能根据数据库`SQL_MODE`中的严格模式判断是否开启。
当前仅会校验int类型字段在写入string值时是否正确。
未进行：
- int等数值类型溢出
- varchar等字符类型的长度溢出
=> update: 添加严格模式下的insert列值检查(string写入int列)

session/session_inception.go
=> update: 优化timestamp字段default null的审核逻辑 (#406)

.github/workflows/go.yml, Makefile, circle.yml, config/config.go, config/config.toml.default, go.mod, session/common.go, session/errors.go, session/session_inception.go, session/session_inception_test.go
添加表列数限制参数`max_column_count`，默认值0表示不限制。
* 建表和添加新字段会受该参数影响
* 该参数默认的审核级别为警告(即 `1` )
=> feature: 添加表列数限制参数max_column_count (#443)

session/session_inception.go
参考：https://github.com/go-sql-driver/mysql/issues/1075
=> update: 解决获取真实行数超时不会返回错误的问题

config/config.go, config/config.toml.default, session/errors.go, session/session_inception.go
https://github.com/hanchuanchuan/goInception/issues/493
=> 1.提供用户添加额外自定义关键字的能力

session/session_inception.go
根据MySQL 5.7及8.0官方文档所示，对添加generated virtual column 为 Only Modifies Medadata。我认为无需经过osc过程对数据库的消耗更低
参考文档:
https://dev.mysql.com/doc/refman/8.0/en/innodb-online-ddl-operations.html#online-ddl-generated-column-operations
https://dev.mysql.com/doc/refman/5.7/en/innodb-online-ddl-operations.html#online-ddl-generated-column-operations
=> 优化MySQL generated virtual column 改表消耗

config/config.go, session/errors.go, session/session_inception.go
在使用过程中，用户有对线上表增加唯一索引的情况，造成了数据丢失
根据issue https://github.com/hanchuanchuan/goInception/issues/227 检查消耗较大
提供一个提示让用户知道风险
=> feat: 增加唯一索引的提醒
