- session/session_inception.go
修复：不允许null约束时，忽略对计算列Generated的nullable检查
**enable_nullable = false** 
`CREATE TABLE `t1`
(
`id`            bigint(20)	unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
`operate_info`  json			not null COMMENT '日志记录',
`type`          tinyint(10)	GENERATED ALWAYS AS (json_extract(`operate_info`, '$.type')) VIRTUAL COMMENT '操作类型',
PRIMARY KEY (`id`)
) ENGINE = InnoDB
COMMENT ='xxx';`
> fix: checkFieldGeneratedNullable

- session/inception_result.go
- session/session.go
- session/session_inception.go
- session/session_inception_split_test.go
- session/session_print.go
实现将一段SQL语句按互不影响原则分组DDL和DML语句，即相同表的DDL及DML语句分开两个语句块执行。
* **用法：** 在调用goInception时，指定 `--split=1` 或 `--enable-split` 选项，指定后，其他选项(审核、执行、备份、打印语法树等)均不再生效。
* **拆分原因：** 兼容老版inception，实际情况下 **可以不分组** ，goInception记录有表结构快照，用以实现binlog解析。
**输出结构：**
* id: 序号列，表示当前行被分成第几个语句块，从1开始
* sql_statement: 表示可以在一起的所有SQL语句, 以分号分隔
* ddlflag: 第三个列表示的是当前被拆之后，可以一起执行的语句中，有没有alter/drop table语句，如果有则输出1，否则输出0，这主要是为了防止在Inception执行这两种语句时有可能带来危险，这样输出之后，可以为上层提供更友好的选择，可以做为一个提醒
* error_message: 错误信息，如果语法错误，则会写入该处，而正常时该值为NULL
> Feature DDL/DML分组功能

- config/config.go
- config/config.toml.default
- config/config.toml.example
- session/errors.go
- session/session_inception.go
- session/session_inception_exec_test.go
- session/session_inception_test.go
主要变动：
- 增加两个参数enable_set_engine、support_engine，移除一个参数enable_not_innodb
- enable_set_engine用于控制是否可以指定表的存储引擎，类似EnableSetCharset
- support_engine用于控制支持的存储引擎类型，类似SupportCharset
- 修改默认配置为`enable_set_engine=true，support_engine="innodb"`
审核举例
- `enable_set_engine=true，support_engine="innodb"`
```
mysql> inception get variables like '%engine%';
+-------------------+--------+
| Variable_name     | Value  |
+-------------------+--------+
| enable_set_engine | true   |
| support_engine    | innodb |
+-------------------+--------+
2 rows in set (0.01 sec)
```
- `enable_set_engine=true，support_engine=""`
```
mysql> inception get variables like '%engine%';
+-------------------+--------+
| Variable_name     | Value  |
+-------------------+--------+
| enable_set_engine | true   |
| support_engine    | | …
```
> update: 增加enable_set_engine、support_engine参数，控制是否允许指定存储引擎以及支持的存储引擎类型

- session/session_inception.go
- session/session_inception_test.go
修复 alter table t1; 命令没有其他选项时能正常通过的bug
> 修复 alter table 命令没有其他选项时能正常通过的bug

- config/config.go
- config/config.toml.example
- session/errors.go
- session/session_inception.go
- session/session_inception_test.go
新增 check_identifier_upper 参数，用于打开表名、列名、索引名大写需求
> 新标识符必须为大写参数

- session/session_inception.go
- session/session_inception_test.go
修复两处异常
- ER_PK_TOO_MANY_PARTS审核信息错误写成ER_TOO_MANY_KEY_PARTS
- ER_TOO_MANY_KEY_PARTS审核信息少了索引名称
> update: 订正两处错误的索引审核信息

- go.mod
- go.sum
- session/common.go
- session/session_inception.go
添加mysql安全连接支持
`ssl` 参数支持以下方式连接（[官网ssl-mode参数说明](https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-mode)）：
- PREFERRED
- REQUIRED
- VERIFY_CA
- VERIFY_IDENTITY
使用CA证书认证时可指定以下参数：
- --ssl-ca
- --ssl-cert
- --ssl-key
> Feature tls connection

- session/session_inception.go
> fix: 修复非空字段insert审核时对自增列的处理 (#113)

- .github/workflows/go.yml
- .travis.yml
- circle.yml
- server/server.go
- session/osc.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
优化在使用pt-osc或gh-ost时的alter子句解析，
支持以下格式(少加了空格，但语法是允许的)
```sql
ALTER TABLE`table1`ADD COLUMN c1 int
```
> 优化pt-osc审核前的ALTER子句拆分

- config/config.go
- config/config.toml.default
- config/config.toml.example
- session/errors.go
- session/session_inception.go
- session/session_inception_test.go
添加以下审核参数：
- `table_prefix` 表名前缀，默认为空，即不限制
- `index_prefix` 普通索引前缀，默认为 `idx_`
- `uniq_index_prefix` 唯一索引前缀，默认为 `uniq_`
**注意：两个索引前缀受开关 `check_index_prefix` 影响。**
> Patch table index prefix

- config/config.go
- config/config_test.go
- session/session_inception.go
可通过下列SQL获取goinception的版本号信息
```sql
inception show variables like 'version';
```
该变更为只读变量, 禁止手动设置值
误设置时会报错 `inception set version="123";`
```
ERROR 1105 (HY000): 只读变量
```
> add: show variables添加版本号信息

- session/osc.go
- session/session_inception_exec_test.go
添加对各种ALTER语法格式的支持
例如:
```sql
-- 这是一条注释
alter table t1 add column c2 varchar(20) comment '!@#$%^&*()_+[]{}\\|;:",.<>/?';
```
```sql
alter table t1 add column `c5` varchar(20) comment \"!@#$%^&*()_+[]{}\\|;:',.<>/?\";  -- 测试注释
```
> fix: 优化使用pt工具时注释导致alter子句解析失败的问题

- parser/parser.go
- parser/parser.y
- session/session_inception.go
- session/session_inception_exec_test.go
- session/session_inception_test.go
- session/tidb_check.go
完善数据类型的显示宽度审核，如以下SQL：
```sql
CREATE TABLE t1(c1 bit(100), 
c2 tinyint(1000), 
c3 smallint(1000), 
c4 mediumint(1000), 
c5 int(1000), 
c6 bigint(1000));
```
> update: 完善数值类型的显示宽度审核 (#162)

- config/config.go
- config/config.toml.default
- config/config.toml.example
- session/osc.go
- session/session.go
- session/session_inception.go
- session/session_inception_exec_test.go
添加参数 `osc_max_flow_ctl` ，对应pt参数 `--max-flow-ctl`。
该参数要求PXC数据库版本大于5.6。已自动添加该处理。
[pt max-flow-ctl参数说明](https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html#cmdoption-pt-online-schema-change-max-flow-ctl)
> new: 添加osc参数max-flow-ctl,以便PXC集群执行pt (#170)

- session/session_inception.go
- session/session_inception_backup_test.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
- session/session_inception_test.go
根据MySQL参数 `innodb_large_prefix` 是否开启来限制单列是否允许超过767字节。
索引的所有列总长度始终不允许超过3072字节。
(未判断InnoDB页大小以及表属性DYNAMIC和COMPRESSED等)
> 优化索引单列长度的767字节限制逻辑

- config/config.go
- config/config.toml.example
- session/errors.go
- session/session_inception.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
- session/session_inception_test.go
审核以下形式的SQL(仅`UPDATE`和`DELETE`)：
```sql
update t1 set c1 = 1 where 123;
update t1 set c1 = 1 where null;
update t1 set c1 = 1 where 1+2;
update t1 set c1 = 1 where 1-2;
update t1 set c1 = 1 where 1*2;
delete from t1 where 1/2;
delete from t1 set c1 = 1 where 1&2;
delete from t1 set c1 = 1 where 1|2;
delete from t1 set c1 = 1 where 1^2;
delete from t1 set c1 = 1 where 1 div 2;
```
审核结果如下(隐藏了部分列)：
order_id |  stage  | error_level |   stage_status   |         error_message        |                    sql      
-----|------|------|-----------|--------------|----------------------------
1     | CHECKED |      0      | Audit Completed |          None         |             use test
2     | CHECKED |      1      | Audit Completed |          Please confirm if you want to use value expression in …
> update: 添加where条件中的值表达式审核,避免无效表达式误更新 (#178)

- config/config.go
- config/config.toml.default
- config/config.toml.example
- tidb-server/main.go
- util/signal/signal_posix.go
终端控制进程结束(终端连接断开)时 会自动发送 `SIGHUP` 信号量以关闭终端子进程，
goinception添加特殊处理，忽略该信号。
为避免该更新产生异常影响，添加新参数 `ignore_sighup` 用以开关该特性。
默认为`true`，开启该特性，即默认 `忽略` SIGHUP信号量
**重要：该参数设置位置和 `port` 或 `[inc]` 配置`同级`。**
可参考 配置文件示例 [config.toml.example](https://github.com/hanchuanchuan/goInception/blob/master/config/config.toml.example)
> update: 添加参数ignore_sighup,默认忽略终端连接断开信号

- config/config.go
- config/config.toml.default
- config/config.toml.example
- session/osc.go
相关ISSUE 见[pt-online-schema-change 中 rename 操作设置超时时间](https://github.com/hanchuanchuan/goInception/issues/214)
> 添加lock_wait_timeout 控制 pt-osc 等待meta lock 时间，默认3s

- config/config.go
- config/config.toml.default
- config/config.toml.example
- docs/options.md
- session/core.go
- session/session_inception.go
- sessionctx/variable/sysvar.go
fix [issue 223](https://github.com/hanchuanchuan/goInception/issues/223)
> 添加lock_wait_timeout,控制普通SQL 执行时的锁等待超时时间

- go.mod
- session/core.go
- session/parser.go
- session/session_inception_backup_test.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
MariaDB v10版本以上时可能出现DML执行成功, 但未生成备份的问题.
问题原因是MariaDB在v10版本的binlog移除了DML操作前的QueryEvent事件, 导致无法获取到DML操作的线程号connection_id.
> fix: 修复MariaDB可能出现dml未备份成功的问题

- session/session_inception.go
修复 `columns_must_have_index` 审核项逻辑。
相关说明：
如果在建表时存在错误，则后续依赖于表结构的审核可能不准确（或者已无法做到准确）
（该问题是否触发取决于审核级别设置）
相关问题：#235
> 修复审核语句存在其他问题时列索引可能审核异常的问题

- session/errors.go
- session/session_inception.go
- session/session_inception_common_test.go
- session/session_inception_test.go
- session/tidb_check.go
索引指定`VISIBLE/INVISIBLE`时是可以通过的，但VISIBLE选项仅在MySQL 8.0版本之后才支持，所以添加该审核规则。
```
-- 示例SQL
create table if not exists t1(id int primary key,c1 char(1));
ALTER TABLE t1
ADD INDEX idx_1 (c1 ASC) VISIBLE;
```
> update: 优化索引可见性审核逻辑,以免后端数据库不支持(fix #247)

- session/session_inception.go
以下`update`语句审核有误，会误报列不存在(指定了表别名但未使用)。
```sql
create table if not exists t1(id int primary key,c1 int);
update t1 a set c1 = 2;
```
> fix: 修复update指定表别名时审核错误的问题(fix #249)

- config/config.go
- config/config.toml.default
- config/config.toml.example
- session/osc.go
update: 增加 pt-osc 执行时 sleep 选项,以优化低配 db 执行 ddl 变更时负载情况
> update: 增加 pt-osc 执行时 sleep 选项,以优化低配 db 执行 ddl 变更时负载情况

- config/config.go
- session/session_inception.go
添加参数`ignore_osc_alter_stmt`, 可配置强制忽略osc的Alter子句, 直接执行.
格式为drop index,add column等,配置要跳过的子句格式,多个时以逗号分隔
例 `ignore_osc_alter_stmt = 'add index,drop index'`
以下格式的语法已自动跳过osc:
```sql
ALTER TABLE tbl_name CHARACTER SET = charset_name;
ALTER TABLE tbl_name COLLATE = 'utf8_bin';
ALTER TABLE tbl_name COMMENT = '...';
```
> feature: 添加参数ignore_osc_alter_stmt可配置忽略osc的alter子句 (#258)

- session/session.go
- session/session_inception.go
- session/session_inception_backup_test.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
- session/session_inception_test.go
- session/tidb_check.go
添加CREATE TABLE AS SELECT语法支持.
会审核mysql参数`enforce_gtid_consistency`和`gtid_mode`参数.
(MySQL的GTID一致性验证可能会报错: `Statement violates GTID consistency: CREATE TABLE ... SELECT.`)
> feature: 添加CREATE TABLE AS SELECT语法支持 (#246)

- session/session.go
- session/session_inception.go
- session/session_inception_test.go
> fix: 修复列歧义性检查对order by可能误报的bug

- session/core.go
- session/session_inception_common_test.go
- session/session_inception_test.go
> update: 优化默认数据库设置的作用范围

- config/config.go
- session/core.go
- session/session.go
- session/session_inception.go
- session/session_inception_common_test.go
- session/session_inception_exec_test.go
仅支持TiDB解析器可正常解析的语法.
安全上有以下强限制: 
1. 用户名必须为root(无论是否开启goinception鉴权功能).因此可通过不同用户名实现权限隔离.
2. 优化级低于现有的功能开关,如禁止删表的话(enable_drop_table=false),则即可允许所有语法也无法执行删除,尽可能保证数据安全性.
3. 该功能为只读变量,不允许通过会话级进行设置
**说明:** 若出现语法错误(在MySQL中正常时),可创建Issue来指出该语法,以便更新SQL解析器.
> feature: 添加enable_any_statement选项以支持所有语法

- ast/ddl.go
不太清楚为何被禁用，开启后可用于支持osc忽略DROP PARTITION
> update: 放开DROP PARTITION的Restore解析

- session/conn.go
- session/inception_result.go
- session/session_inception.go
当连接超时时自动重连数据库。
内置限制：仅在超时设置不小于600s(即10分钟)时开启该功能(参数`wait_timeout`)，以免错误重连。
相关问题： #306
> update: 优化数据库连接超时时的处理(#306)

- session/session_inception.go
- session/session_inception_exec_test.go
目前的判断会导致有任意需要忽略的语句块就会忽略整个语句，比如删除索引重建会忽略osc执行
```
Inc.IgnoreOscAlterStmt = "drop index,drop partition"
sql = "alter table t1 drop index ix,add index ix2(c1);"
```
> fix: 修复强制忽略osc的判断问题，语句中有任意需要使用osc执行的都不能忽略

- config/config.go
- session/session_inception.go
- session/session_inception_exec_test.go
添加参数`max_execution_time`的设置，来控制DML语句的最大执行时间
关联PR: #304
> feature: 添加选项max_execution_time设置会话级DML语句的最大执行时间

- session/session_inception.go
- session/session_inception_backup_test.go
修复当执行类似如下SQL时，除第一个表外，其他表名在审核时会报找不到的错误。
```sql
rename table t1 to t1_old,t2 to t1;
```
关联：#307
> fix: 修复rename table语法一次修改多个表名时，有表名逻辑上不生效的问题 (#307)

- session/common.go
- session/parser.go
- session/session_inception.go
- session/session_inception_backup_test.go
在修改或删除包含有计算列的行时，未忽略计算列会导致DML回滚语句有误。
关联：#324
> fix: 修复dml回滚语句未忽略计算列的问题(#324)

- .github/workflows/go.yml
- Dockerfile
- Makefile
- circle.yml
- config/config.go
- session/osc.go
- session/session_inception.go
- session/session_inception_exec_test.go
- util/processinfo.go
功能开关参数：`ghost_bin_dir`，使用方式和pt-online-schema-change的`osc_bin_dir`参数一样。
在启用gh-ost方式执行ALTER变更时，若配置了`ghost_bin_dir`参数，则以binary方式调用外部的gh-ost，否则仍以默认的内置gh-ost来执行。
关联问题：#305
> update: 拆分gh-ost模块，支持binary方式调用gh-ost，以优化gh-ost源码内置带来的问题

- session/common.go
- session/inception_masking_test.go
- session/session.go
- session/session_inception.go
- session/session_masking.go
*** 语法树功能升级
返回解析和原语法树查询功能一致(引用自文档[语法树说明](https://hanchuanchuan.github.io/goInception/tree.html))
1. ID：这个用来表示当前语句的一个序列值。
2. STATEMENT：这个列用来存储当前被分析的SQL语句。
3. ERRLEVEL：这个列用来存储当打印遇到问题时，错误的级别，与审核结果集中的ERRLEVEL意义相同。
4. QUERY_TREE：这个列就是对当前语句的分析结果，格式为JSON字符串。
5. ERRMSG：这个列与上面的ERRLEVEL对应，当出错时，这里存储分析过程中所有的错误信息，与审核结果集中的同名列意义相同。
其中,唯一有改动的`QUERY_TREE`返回格式如下:
```sql
select MOD(id,2)as col1,IFNULL(c1,id) from t1; -- 示例SQL
```
```json
[
{
"index":0,
"field":"id",
"type":"int(11)",
"table":"t1",
"schema":"test_inc",
"alias":"col1"
},
{
"index":1,
"field":"c1",
"type":"int(11)",
"table":"t1",
"schema":"test_inc",
"alias":"IFNULL(c1,id)"
},
{
"index":1,
"field":"id",
"type":"int(11)",
"table":"t1",
"schema":"test_inc",
"alias":"IFNULL(c1,id)"
}
]
```
字段说明:
* index: 列索引,标识为第几列,可能重复(如函数引用了多列时)
* field: 原始列名
* …
> feature: 添加masking功能-语法树解析功能升级,返回select涉及的对象(库.表.列)

- session/session_inception.go
#364 问题：TiDB check 时返回结果为 0。
TiDB 不同版本explain 差异，是否考虑使用`strconv.ParseFloat` 而不是 `strconv.Atoi`
1、3.0.19 explain 返回的 count
```
MySQL [xxx]> select version();
+---------------------+
| version()           |
+---------------------+
| 5.7.25-TiDB-v3.0.19 |
+---------------------+
1 row in set (0.00 sec)
MySQL [xxx]> explain delete from temp_vip_xxx where id = 1;
+-------------------+-------+------+---------------------------------+
| id                | count | task | operator info                   |
+-------------------+-------+------+---------------------------------+
| Delete_2          | N/A   | root | N/A                             |
| └─Point_Get_1     | 1.00  | root | table:temp_vip_xxx, handle:1 |
+-------------------+-------+------+---------------------------------+
2 rows in set …
```
> 修复TiDB check结果affected_rows返回0的问题

- session/session_inception.go
在goInception使用过程中,主键不会为null  ，这里可以不用设置为not null
> primary key 不会为null 这里可以排除primay

- tidb-server/main.go
这是一种案例，主要参数还是从配置文件读取，少量配置例如bakcup_host等相关信息从env读取后和配置文件合并；方便k8s大量快速部署给客户，希望可以抛砖引玉。
> add: cofiguration support environment variables

- tidb-server/main.go
这是一种案例，主要参数还是从配置文件读取，少量配置例如bakcup_host等相关信息从env读取后和配置文件合并；方便k8s大量快速部署给客户，希望可以抛砖引玉。
本次pr，修正上次提交变量名不规范的行为；参数命名为全大写加下划线格式, 如BACKUP_HOST等.
https://github.com/hanchuanchuan/goInception/pull/503
> fix: cofiguration support environment variables

- session/common.go
- session/const.go
- session/session_inception.go
Support OceanBase query plan format `OceanBaseExplainInfo` in `getExplainInfo` method.
The original output of explain statement is not in standard table format, for example:
```
mysql> EXPLAIN delete from user where id = 1;
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Query Plan …
```
> [oceanbase] support affected rows in query explain

- session/const.go
- session/errors.go
- session/session_inception.go
Here we deal with following DDL on OceanBase and return error:
- Alter table add column with PK or UK
- Alter table drop column with index or PK
- Alter table change column type
- Alter table change character set or collation
> [oceanbase] return error when ddl is not supported

- config/config.go
- session/osc.go
当调用外部gh-ost时，添加timestamp-old-table 选项的解析和默认值
> add timestamp-old-table parser

- config/config.go
- session/common.go
- session/inception_result.go
- session/session.go
- session/session_inception.go
- session/tidb.go
新增 check-merge参数，设置其为1后开启自动合并alter table语句功能（现在仅有命令行参数，后续将添加配置文件参数并将参数名修改为 alter-auto-merge）。在添加了check-merge参数后，goInc会检查用户提交的SQL，并将其中涉及相同表的alter table，create index，drop index语句统一合并为 alter table语句，然后返回SQL检查结果以及合并后新生成的SQL。
goInc校验的返回值增加了一个字段，显示对应的SQL是否为 (alter table|create index|drop index)， 如果是的话，就会显示'alterTable'字样。对于合并后新生成的SQL，ErrorMessage字段显示"Merged"。以上两个字段可用于区分是原有SQL还是合并后的SQL
新增alterTableInfo结构体，记录每一个表被修改的信息，包括表名，所有alter语句的语法树，以及合并后的新SQL
在checkAlterTable方法中写入alterTableInfo，在提交阶段进行SQL的合并工作，通过合并语法树然后生成新的SQL
对于create index和drop index语句，使用convertCreateIndexToAddConstrain和convertDropIndexToDropIndex方法（已修改成convertCreateIndexToAlterTable和convertDropIndexToAlerTable）将其转换为alter table语句，然后进行合并。
> 增加在SQL审核阶段自动识别并合并相同表的alter table语句的功能

- config/config.go
- config/config.toml.default
- session/session_inception.go
> update: optimize mysql v8.0 ddl instant check (#668)
